Update README
Primordus/lua-quickcheck pull request #30
Opened 2021-04-09 08:10 UTC by ligurio

- describe usage with external test-runners
- describe builtin generators

2021-04-13 06:45 UTC, luc-tielen requested changes
Left some minor suggestions, looks good for the rest.

Thanks!

2021-04-13 06:45 UTC, luc-tielen commented on README.md
> +Lua QuickCheck exposes a test-runner as a command-line interface for running
```suggestion 
### Using the LQC test runner

Lua QuickCheck exposes a test-runner as a command-line interface for running
```

2021-04-13 06:45 UTC, luc-tielen commented on README.md
> +In more or less mature projects tests already exist and run using test-runner
```suggestion
### Using an external test runner

In mature projects tests already exist and run using test-runner
```

2021-04-13 06:45 UTC, luc-tielen commented on README.md
> +testcase.
```suggestion
test-runners.  In such cases it is still possible to use Lua QuickCheck.
All you need to do is import required modules and run `lqc.check()` in
each testcase.
```

2021-04-13 06:45 UTC, luc-tielen commented on README.md
> +Below is example of test `test/sum_test.lua` to use with `luatest` library
```suggestion
Below is an example of test `test/sum_test.lua` for use with the `luatest` library:
```

2021-04-13 06:45 UTC, luc-tielen commented on README.md
> +And similar with test library `busted`:
```suggestion
And here's an example with test library `busted`:
```

2021-04-13 06:45 UTC, luc-tielen commented on README.md
> +To run test execute: `busted spec/sum_spec.lua`
```suggestion
To run the tests, execute the following command: `busted spec/sum_spec.lua`
```

2021-04-13 10:59 UTC, ligurio commented
> Left some minor suggestions, looks good for the rest.

Thanks for suggestions! Everything committed, squashed (also I have added `Co-authored-by` to mark you as co-author) and force-pushed.
Seems change with descriptions for generators requires review too - I'm stuck with description for some of them.

2021-04-13 13:25 UTC, ligurio commented
Unfortunately CI is broken, sorry for that.
I'll fix it in a separate commit in the same PR (if you have no objections).
right now it can start, but
- Lua == 5.1 failed due to segmentation fault in busted (https://github.com/luc-tielen/lua-quickcheck/pull/30/checks?check_run_id=2333602586)
- LuaJIT jobs failed to upload code coverage data:
```
Uploading ...
Upload error: Couldn't find a repository matching this job.
Raw data:	Couldn't find a repository matching this job.
--------------------
Upload error: Couldn't find a repository matching this job.
Raw data:	Couldn't find a repository matching this job.
--------------------
```

2021-04-15 20:10 UTC, luc-tielen commented
@ligurio Yeah, it never is that easy to switch over CI.. I'd look into the segfault first. If we can't fix that; we might have to go back to old way of CI? :thinking:

2021-04-16 07:49 UTC, ligurio commented
> Yeah, it never is that easy to switch over CI.. I'd look into the segfault first. If we can't fix that; we might have to go back to old way of CI?

I suspect the root cause is not in CI itself but in actions described by me. CI workflow runs on Ubuntu 20.04, I have the same OS on my laptop and everything works fine there. I'll try to investigate problem more and try to fix it.

2021-04-16 14:11 UTC, ligurio commented
I have found a [ticket](https://github.com/moteus/luacov-coveralls) about random luajit segfaults on running busted and also related [conversation](https://www.freelists.org/post/luajit/random-segfaults-when-running-tests-with-busted) in luajit mailing list.
Someone suggested a [solution](https://github.com/Olivine-Labs/luassert/pull/150) with small Lua snippet. I have applied it to lua-quickcheck and now CI is red but due to failed steps with upload code coverage data to coveralls service. I suspect `lua-coveralls` requires environment variable with coveralls token (see https://github.com/moteus/luacov-coveralls).

For me this solution looks like a dirty hack.

2021-04-20 20:27 UTC, luc-tielen commented
@ligurio maybe we should split this PR into multiple parts? Just README docs in this 1, fixing CI in another? CI is broken anyway, so I will merge in when docs are updated.

2021-04-20 20:31 UTC, ligurio commented
Agree. I have failed to fix CI quickly so it's better to split PRs. I'll do.

2021-04-21 07:37 UTC, ligurio commented
@luc-tielen done

2021-04-21 20:21 UTC, luc-tielen approved these changes

2021-04-21 20:22 UTC, merged